[http]
listen = 0.0.0.0:8080

[sessions]
# Generer avec: openssl rand -hex 32
hashkey = CHANGE_ME_64_HEX_CHARS

# DOIT faire exactement 16, 24 ou 32 OCTETS (donc openssl rand -hex 16 pour 32 caracteres)
blockkey = CHANGE_ME_32_CHARS_EXACT

[clients]
# Generer avec: openssl rand -hex 32
internalsecret = CHANGE_ME_64_HEX_CHARS

[backend]
backends = homelab
allowall = false
timeout = 10
connectionsperhost = 8

[homelab]
urls = https://nextcloud.noschoixpourvous.com
# Doit correspondre au secret utilise avec: occ talk:signaling:add
secret = CHANGE_ME_64_HEX_CHARS

[nats]
url = nats://loopback

[mcu]
type =

[geoip]
license =

[stats]
allowed_ips =
